# Generated by Django 2.0.2 on 2018-03-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_calculator'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutamount',
            name='historical_usd_to_eth',
            field=models.FloatField(default=850),
            preserve_default=False,
        ),
    ]
